language: python
python:
- '3.6'
script: true
deploy:
  provider: pypi
  user: fridex
  password:
    secure: HWVfVk+nEsGZXf8dUcPyZwsg1tBHp6nZzoyffI26QOx5L8JI8aG17V5mFeL5mXi9/IupCVLfQGTMI+NV9cBF0NtqdnkXNS7UevtVNgeI8PRnSkzdUoaQOZ35CShtr6sBmnEYpbxZToUyuBxZ19xODYRmhR8FVDy+0276ns66gOAHnETiIv0siF9NsNaGvPsTuRAPzl6Vnrc4lkME9kyx/RWS4utUr7p4nfJfU3R2P+pxkL1F0n86SDXTJtNCibOP1b7AW93h8+9PASZBoUuFdLoqFFhN4YFtPJjo8Q/0EBdaMr5Zy0BgtTR5+Ixpzs3uGuDQy2vDcTOboA/EdPXjYMbiZUfL2MVOeGAwG3zl6wND7EmsgehoaekGe/SNDbzzCRAGnK0ef5t5z0P0gOKE63qnJb40/jst4V6PxPEDUz76AEYbOjwFdkZkRlIfqTgUTq5FJWI9JjkBhVOslGfMS4EglMHG4MFCqrg+HwCrLH3HcJvOZKB7xlX6bP3I795QJVf9N8HTdK9NTKIfM3CG9jNlEnIgRy1jM+dh8bm/gn2Rn8CDc7tIucyn9WOJLMvXxlG1NrkFpIpErzr5j2Wxx6G+vBdXw9C+3GcPQSUL3a3L1w1L9ouaGREk5mRTY6uFxiSyTWKxHEMmYCbcUsJmQ9DsJr6SuTHNvjGl/XRmlbE=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
